export const DATA_REQUEST = "DATA_REQUEST";
export const DATA_SUCCESS = "DATA_SUCCESS";
export const DATA_SAVE_SUCCESS = "DATA_SAVE_SUCCESS";
export const DATA_ERROR = "DATA_ERROR";

export const USER_REQUEST = "USER_REQUEST";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_NOT_FOUND = "USER_NOT_FOUND";
export const USER_WRONG_PASSWORD = "USER_WRONG_PASSWORD";
export const USER_ERROR = "USER_ERROR";
export const USER_LOGOUT = "USER_LOGOUT";

export const UNREAD_NOTIFICATION_AMOUNT_REQUEST =
  "UNREAD_NOTIFICATION_AMOUNT_REQUEST";
export const UNREAD_NOTIFICATION_AMOUNT_SUCCESS =
  "UNREAD_NOTIFICATION_AMOUNT_SUCCESS";
export const UNREAD_NOTIFICATION_AMOUNT_ERROR =
  "UNREAD_NOTIFICATION_AMOUNT_ERROR";
export const READ_NOTIFICATION = "READ_NOTIFICATION";

export const SKILL_NAMES_REQUEST = "SKILL_NAMES_REQUEST";
export const SKILL_NAMES_SUCCESS = "SKILL_NAMES_SUCCESS";
export const SKILL_NAMES_ERROR = "SKILL_NAMES_ERROR";

export const STAGE_TYPES_REQUEST = "STAGE_TYPES_REQUEST";
export const STAGE_TYPES_SUCCESS = "STAGE_TYPES_SUCCESS";
export const STAGE_TYPES_ERROR = "STAGE_TYPES_ERROR";
