export const DATA_REQUEST = "DATA_REQUEST";
export const DATA_SUCCESS = "DATA_SUCCESS";
export const DATA_ERROR = "DATA_ERROR";

export const USER_REQUEST = "USER_REQUEST";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_NOT_FOUND = "USER_NOT_FOUND";
export const USER_WRONG_PASSWORD = "USER_WRONG_PASSWORD";
export const USER_ERROR = "USER_ERROR";
export const USER_LOGOUT = "USER_LOGOUT";

export const UNREAD_NOTIFICATION_AMOUNT_REQUEST =
  "UNREAD_NOTIFICATION_AMOUNT_REQUEST";
export const UNREAD_NOTIFICATION_AMOUNT_SUCCESS =
  "UNREAD_NOTIFICATION_AMOUNT_SUCCESS";
export const UNREAD_NOTIFICATION_AMOUNT_ERROR =
  "UNREAD_NOTIFICATION_AMOUNT_ERROR";
