export const RESULTS_BY_YEAR_REQUEST = 'RESULTS_BY_YEAR_REQUEST'
export const RESULTS_BY_YEAR_SUCCESS = 'RESULTS_BY_YEAR_SUCCESS'
export const RESULTS_BY_YEAR_ERROR = 'RESULTS_BY_YEAR_ERROR'

export const ACTUAL_SCHEDULE_REQUEST = 'ACTUAL_SCHEDULE_REQUEST'
export const ACTUAL_SCHEDULE_SUCCESS = 'ACTUAL_SCHEDULE_SUCCESS'
export const ACTUAL_SCHEDULE_ERROR = 'ACTUAL_SCHEDULE_ERROR'

export const USER_REQUEST = 'USER_REQUEST'
export const USER_SUCCESS = 'USER_SUCCESS'
export const USER_NOT_FOUND = 'USER_NOT_FOUND'
export const USER_WRONG_PASSWORD = 'USER_WRONG_PASSWORD'
export const USER_ERROR = 'USER_ERROR'
export const USER_LOGOUT = 'USER_LOGOUT'
